export const state = {
  lang: 'zh-CN',
  device: 'desktop',
  layout: 'top',
  navTheme: 'light',
  contentWidth: 'Fluid',
  fixedHeader: true,
  fixedSidebar: false,
  menu: {
    locale: false,
  },
  splitMenus: false,
  title: '教师公共服务系统',
  primaryColor: '#bb133e',
  colorWeak: false,
  transitionName: '',
  multiTab: true,
  multiTabFixed: false,
  // lang: 'en-US',
  // device: 'desktop',
  // layout: 'side',
  // navTheme: 'dark',
  // contentWidth: 'Fluid',
  // fixedHeader: false,
  // fixedSidebar: true,
  // menu: {
  //   locale: false,
  // },
  // splitMenus: false,
  // title: '教师公共服务系统',
  // primaryColor: '#bb133e',
  // colorWeak: false,
  // transitionName: '',
  // multiTab: true,
  // multiTabFixed: false,
};
